### ISSUE TITLE
Runtime error while generating coverage results

### ISSUE THREAD

**Issue by kunom** [TimSVector/vc_scripts_submodule#1]
As of 3e6f81f79c77558fe34e1af8a83d98cf10256f2a, I get the following stack trace:

```
Traceback (most recent call last):
  File "C:\vc_scripts_submodule\vcast_exec.py", line 349, in <module>
    vcExec.runLcovMetrics()
  File "C:\vc_scripts_submodule\vcast_exec.py", line 210, in runLcovMetrics
    generate_lcov.generateCoverageResults(self.FullMP, self.xml_data_dir, verbose = self.verbose)
  File "C:\vc_scripts_submodule\generate_lcov.py", line 236, in generateCoverageResults
    output = runCoverageResultsMP(inFile, verbose=verbose)
  File "C:\vc_scripts_submodule\generate_lcov.py", line 94, in runCoverageResultsMP
    return runGcovResults(api, verbose = False)
  File "C:\vc_scripts_submodule\generate_lcov.py", line 194, in runGcovResults
    for fn, fdna in FN, FDNA:
NameError: name 'FDNA' is not defined
```

Looks like it should be named `FNDA`.

**Comment by TimSVector** [comment]
Fixed and pushed.  Thanks!

**Comment by TimSVector** [comment]
closing

**Comment by kunom** [comment]
Not sure whether I get it correct, but with your latest commit you introduced another dependency that I cannot find:

```
C:\temp>vpython c:\vc_scripts_submodule\vcast_exec.py --build-execute c:\VCAST\Environments\Some_Project.vcm --junit --cobertura --lcov --aggregate --metrics --fullstatus
Traceback (most recent call last):
  File "c:\vc_scripts_submodule\vcast_exec.py", line 29, in <module>
    import cobertura
  File "c:\vc_scripts_submodule\cobertura.py", line 42, in <module>
    from vcast_utils import dump, checkVectorCASTVersion
ModuleNotFoundError: No module named 'vcast_utils'
```

**Comment by TimSVector** [comment]
I missed a new file on the commit.  Should be good to go
